### ISSUE TITLE
no more "blead" perl in .travis.yml

### ISSUE THREAD

**Issue by powerman** [leejo/cgi-fast#10]
Travis didn't has blead anymore, it just repeat tests on 5.14.

**Comment by leejo** [comment]
Think this is just a spurious error/warning. If you look at https://travis-ci.org/leejo/cgi-fast/jobs/51777330 (line 145) perl -V returns 5.21.10 so i think blead is working OK. I have raised https://github.com/travis-perl/helpers/issues/13

**Comment by powerman** [comment]
Oh, I see, problem is I didn't knew about travis-perl project and use only native Travis perl support, that's why I didn't have blead perl. Sorry for false report.
