### ISSUE TITLE
Contradicting license statements

### ISSUE THREAD

**Issue by ppisar** [leejo/cgi-fast#13]
CGI-Fast-2.09's lib/CGI/Fast.pm reads at the beginning:

```
# Copyright 1995,1996, Lincoln D. Stein.  All rights reserved.
# It may be used and modified freely, but I do request that this copyright
# notice remain attached to the file.  You may modify this module as you
# wish, but if you redistribute a modified version, please attach a note
# listing the modifications you have made.
```

and at the end:

```
=head1 LICENSE

Copyright 1996-1998, Lincoln D. Stein.  All rights reserved. Currently
maintained by Lee Johnson

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
```

The issue is that Perl is licensed as "GPL or Artistic" and GPL forbids any additional constrains. In my point of view the "attach a note listing the modifications" is one of these incompatible additional requirements.

I believe this is just a mistake (maybe o quotation from the Artistic license) and it would be great if you made the license statements better. For example by removing the first statement.

**Comment by leejo** [comment]
Given the date of the license hasn't been updated in, oh, 17 years, i'm not so sure this is that big a deal. I'll strip out the top comment, i'm sure it won't bother Lincoln.
