### ISSUE TITLE
Still secretly needs Test::Deep

### ISSUE THREAD

**Issue by kentfredric** [leejo/cgi-fast#17]
https://metacpan.org/source/LEEJO/CGI-Fast-2.12/Changes#L33-35
> 2.05 2014-12-11
>    [TESTING]
>    remove useless use of Test::Deep in tests

https://github.com/leejo/cgi-fast/blob/master/t/003_env_pollution.t#L7

> ```perl
> use Test::More tests => 5;
> use Test::Deep;
> ```

META.json since 2.006 has not declared TEST_REQUIRES of `Test::Deep`

https://metacpan.org/diff/file?target=LEEJO%2FCGI-Fast-2.06%2F&source=LEEJO%2FCGI-Fast-2.05#META.json

> ```diff
> @@ -22,10 +22,7 @@
>     },
>     "prereqs" : {
>        "build" : {
> -         "requires" : {
> -            "Test::Deep" : "0.11",
> -            "Test::More" : "0"
> -         }
> +         "requires" : {}
>        },
>        "configure" : {
>           "requires" : {}
> @@ -33,10 +30,8 @@
>        "runtime" : {
>           "requires" : {
>              "CGI" : "4",
> +            "Carp" : "0",
>              "FCGI" : "0.67",
> -            "File::Spec" : "0.82",
> -            "Test::Deep" : "0.11",
> -            "Test::More" : "0.98",
>              "if" : "0",
>              "perl" : "5.008001"
>           }
> ```

The lack of failures is held together by the skeleton effect of Makefile.PL restoring those dependencies in the generated MYMETA.json combined with `dynamic_config: 1`

https://github.com/leejo/cgi-fast/blob/master/Makefile.PL#L19-L22

> ```perl
>     TEST_REQUIRES   => {
>         'Test::More'      => 0,
>         'Test::Deep'      => 0.11,
>         'File::Temp'      => 0,
>     },
> ```

But it should still be considered a regression that tests unconditionally need Test::Deep, and neither META.json or META.yml  stipulate Test::Deep in any way.

**Comment by leejo** [comment]
Thanks! v2.13 will be on its way to CPAN shortly.
