### ISSUE TITLE
Lack of usage warning

### ISSUE THREAD

**Issue by Grinnz** [leejo/cgi-fast#18]
CGI::Fast has all of the same problems as CGI.pm (except for being stuck with the CGI non-persistent protocol), as it's simply a subclass, and introduces more as FCGI is a bit buggy. It would probably be a good idea to add a section referring to CGI::Alternatives like CGI.pm has, as plackup can serve FastCGI as well.

**Comment by leejo** [comment]
v2.14 on its way to CPAN. Thanks!
