### ISSUE TITLE
cpan install error on cygwin

### ISSUE THREAD

**Issue by dougseay** [leejo/cgi-fast#20]
[dispsym:master] => perl -v

This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-cygwin-threads-multi
(with 7 registered patches, see perl -V for more detail)

[dispsym:master] => cpan test CGI::Fast
Reading '/home/dseay/.cpan/Metadata'
  Database was generated on Thu, 19 Aug 2021 00:17:03 GMT
Could not expand [test]. Check the module name.
I can suggest names if you provide the -x option on invocation.
Skipping test because I couldn't find a matching namespace.
Running install for module 'CGI::Fast'
CPAN: Digest::SHA loaded ok (v6.02)
CPAN: Compress::Zlib loaded ok (v2.093)
Checksum for /home/dseay/.cpan/sources/authors/id/L/LE/LEEJO/CGI-Fast-2.15.tar.gz ok
CPAN: YAML loaded ok (v1.30)
CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
CPAN: Parse::CPAN::Meta loaded ok (v2.150010)
CPAN: CPAN::Meta loaded ok (v2.150010)
Configuring L/LE/LEEJO/CGI-Fast-2.15.tar.gz with Makefile.PL
CPAN: CPAN::Reporter loaded ok (v1.2018)
Checking if your kit is complete...
Looks good
Warning: LINKTYPE set to '', no longer necessary
Generating a Unix-style Makefile
Writing Makefile for CGI::Fast
Writing MYMETA.yml and MYMETA.json
  LEEJO/CGI-Fast-2.15.tar.gz
  /usr/bin/perl Makefile.PL -- OK
Running make for L/LE/LEEJO/CGI-Fast-2.15.tar.gz
CPAN: Module::CoreList loaded ok (v5.20210123)
cp lib/CGI/Fast.pm blib/lib/CGI/Fast.pm
Manifying 1 pod document
  LEEJO/CGI-Fast-2.15.tar.gz
  /bin/make -- OK
CPAN: CPAN::DistnameInfo loaded ok (v0.12)
Running make test for LEEJO/CGI-Fast-2.15.tar.gz
PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/001_basic.t .............. ok
t/002_import.t ............. ok
t/003_env_pollution.t ...... ok
t/004_fcgi_file_handles.t .. ok
t/005_no_file_handles.t .... ok
t/006_changes.t ............ ok
t/007_socket_perm.t ........ 1/?
#   Failed test 'socket has default perms'
#   at t/007_socket_perm.t line 29.
#          got: '420'
#     expected: '493'
# Looks like you failed 1 test of 9.
t/007_socket_perm.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests

Test Summary Report
-------------------
t/007_socket_perm.t      (Wstat: 256 Tests: 9 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=7, Tests=57,  4 wallclock secs ( 0.01 usr  0.27 sys +  0.95 cusr  2.77 csys =  4.00 CPU)
Result: FAIL
Failed 1/7 test programs. 1/57 subtests failed.
make: *** [Makefile:878: test_dynamic] Error 1
  LEEJO/CGI-Fast-2.15.tar.gz
  /bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports LEEJO/CGI-Fast-2.15.tar.gz
cpan failed: rc=1
[dispsym:master] =>

**Comment by leejo** [comment]
Thanks! v2.16 on its way to CPAN.
